### ISSUE TITLE
gdash HTTP500 

### ISSUE THREAD

**Issue by zzzhangqi** [kadalu/gdash#18]
hello，I Start gdash service in any one of the Gluster server node. access http://localhost:8080, Console error：
```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib64/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib64/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/cherrypy/lib/jsontools.py", line 59, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/gdash/__main__.py", line 99, in volumes
    return volume.status_detail(group_subvols=True)
  File "/usr/local/lib/python3.7/site-packages/glustercli/cli/volume.py", line 187, in status_detail
    return parse_volume_status(volume_execute_xml(cmd),
  File "/usr/local/lib/python3.7/site-packages/glustercli/cli/utils.py", line 134, in volume_execute_xml
    return gluster_execute_xml(cmd)
  File "/usr/local/lib/python3.7/site-packages/glustercli/cli/utils.py", line 119, in gluster_execute_xml
    return execute_or_raise(cmd)
  File "/usr/local/lib/python3.7/site-packages/glustercli/cli/utils.py", line 102, in execute_or_raise
    raise GlusterCmdException((returncode, out, err))
glustercli.cli.utils.GlusterCmdException: (1, 'Connection failed. Please check if gluster daemon is operational.\n', '')
```
The start command is `gdash localhost`,`gdash  host machine ip`，It's the same error

How can I deal with it?

thank you

**Comment by zzzhangqi** [comment]
kadalu normal，Can mount pvc

**Comment by amarts** [comment]
@zzzhangqi currently, we don't have any 'dashboard' for kadalu. This project was enhanced from aravindavk/gdash to provide a dashboard for any glusterfs deployment.

**Comment by amarts** [comment]
if you are using kadalu with `External` gluster, then you can use this to monitor external gluster.

**Comment by aravindavk** [comment]
Kadalu Storage is not using Glusterd for managing the Gluster processes and volumes, so Glusterd is not started in server pods. Gdash runs Gluster CLI which gets information from Glusterd.

We may introduce, UI based management for Kadalu Storage management in K8s. Let us know what all things you want to see in the dashboard. (Enclosed the dashboard idea which includes Storages, Storage Classes, Pods, Pvs)

![IMG_2816](https://user-images.githubusercontent.com/338230/101158535-e78d9a80-3651-11eb-96d7-18400d8e1a3c.jpg)

**Comment by zzzhangqi** [comment]
Thank you for reply
How can I use gdash in Kadalu？
