### ISSUE TITLE
ImportError: No module named ext.cache

### ISSUE THREAD

**Issue by noahzaozao** [kadalu/gdash#7]
[root@localhost trunk]# gdash 
Traceback (most recent call last):
  File "/usr/bin/gdash", line 9, in <module>
    load_entry_point('gdash==0.4', 'console_scripts', 'gdash')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/gdash/app.py", line 12, in <module>
    from flask.ext.cache import Cache
ImportError: No module named ext.cache

**Comment by tag1970** [comment]
Hi! Change imported module to flask_cache.

**Comment by mutton44** [comment]
> Hi! Change imported module to flask_cache.
"flask.ext.cache" to "flask_cache" in /usr/lib/python2.7/site-packages/gdash/app.py 
Throws out another error in jinja2ext. Did the same change for that file. Now works!

**Comment by aravindavk** [comment]
Fixed now with the latest release. Gdash is rewritten using CherryPy and ReactJS
